<?php
$mycanvas=imagecreate($_GET['c1'],$_GET['c2']);
$clr=ImageColorallocate($mycanvas,0,255,255);
$clr1=imagecolorallocate($mycanvas,$_GET['red'],$_GET['green'],$_GET['blue']);
//imagerectangle($mycanvas,60,60,300,200,$clr);
imagefilledarc($mycanvas,$_GET['x1'],$_GET['x2'],$_GET['x3'],$_GET['x4'],$_GET['x5'],$_GET['x6'],$clr1,IMG_ARC_PIE);
//imagefilledrectangle($mycanvas,700,40,450,150,$clr1);
header("content-type:image/png");
imagepng($mycanvas);
?>